name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build project and Build the Docker image
      run: |
        yarn
        yarn run build
        docker build . --file Dockerfile --tag gudongn/try-mock-vue:latest

    - name: Login Docker and Push the Docker image
      run: |
        docker login -u gudongn -p 3fa7dbde-f973-4792-b74a-d3f5fe1f0f61
        docker push gudongn/try-mock-vue:latest
